export const userList = {
  records: [
    {
      userId: 40,
      username: 'admin',
      password: '$2a$10$sWH.qQmf/dHMURzE4kN0puBOdB7VWwcDFB2NvwpMaHYz6OFZwQGBy',
      nickname: '管理员',
      avatar: 'https://cdn.eleadmin.com/20200610/avatar.jpg',
      sex: '2',
      phone: '12345678901',
      email: 'eleadmin@eclouds.com',
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: '2021-05-21',
      introduction: '遗其欲，则心静！',
      organizationId: 31,
      status: 0,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-01-13 14:43:52',
      updateTime: '2023-04-10 15:08:51',
      organizationName: 'XXX公司',
      sexName: '女',
      roles: [
        {
          roleId: 10,
          roleCode: 'admin',
          roleName: '管理员',
          comments: '管理员',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:37',
          updateTime: '2020-03-21 15:15:54',
          userId: 40
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: true,
      accountNonExpired: true,
      credentialsNonExpired: true
    },
    {
      userId: 41,
      username: 'user01',
      password: '$2a$10$y3j0Bnn4cMOErMLv31LUw.Drs/xs1peDQwT7YYHJbFX6xGDQcXUaK',
      nickname: '用户一',
      avatar:
        'https://cdn.eleadmin.com/20200609/c184eef391ae48dba87e3057e70238fb.jpg',
      sex: '2',
      phone: '12345678902',
      email: null,
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: null,
      introduction: null,
      organizationId: 31,
      status: 0,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-09-15 17:49:37',
      updateTime: '2024-06-11 03:30:31',
      organizationName: 'XXX公司',
      sexName: '女',
      roles: [
        {
          roleId: 11,
          roleCode: 'user',
          roleName: '普通用户',
          comments: '普通用户',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:52',
          updateTime: '2020-03-21 15:16:02',
          userId: 41
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: true,
      accountNonExpired: true,
      credentialsNonExpired: true
    },
    {
      userId: 42,
      username: 'user02',
      password: '$2a$10$fF2qbzA1.zIOUZpedxtvoubQ9doxlSNSunGQLwYxnvSqM8Wx6AeGC',
      nickname: '用户二',
      avatar: null,
      sex: '1',
      phone: '12345678903',
      email: null,
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: null,
      introduction: null,
      organizationId: 31,
      status: 0,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-09-15 17:50:20',
      updateTime: '2023-05-24 23:21:38',
      organizationName: 'XXX公司',
      sexName: '男',
      roles: [
        {
          roleId: 11,
          roleCode: 'user',
          roleName: '普通用户',
          comments: '普通用户',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:52',
          updateTime: '2020-03-21 15:16:02',
          userId: 42
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: true,
      accountNonExpired: true,
      credentialsNonExpired: true
    },
    {
      userId: 43,
      username: 'user03',
      password: '$2a$10$iP1vojXrDgjTaU6ZY3dGfefXGmyftJbPhTuU7cWBxkNI3w20WwZOW',
      nickname: '用户三',
      avatar: null,
      sex: '2',
      phone: '12345678904',
      email: null,
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: null,
      introduction: null,
      organizationId: 31,
      status: 0,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-09-15 17:50:51',
      updateTime: '2023-06-02 00:11:21',
      organizationName: 'XXX公司',
      sexName: '女',
      roles: [
        {
          roleId: 11,
          roleCode: 'user',
          roleName: '普通用户',
          comments: '普通用户',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:52',
          updateTime: '2020-03-21 15:16:02',
          userId: 43
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: true,
      accountNonExpired: true,
      credentialsNonExpired: true
    },
    {
      userId: 44,
      username: 'user04',
      password: '$2a$10$iMsEmh.rPlzwy/SVe6KW3.62vlwqMJpibhCF9jYN.fMqxdqymzMzu',
      nickname: '用户四',
      avatar: null,
      sex: '1',
      phone: '12345678905',
      email: null,
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: null,
      introduction: null,
      organizationId: 32,
      status: 0,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-09-15 17:51:50',
      updateTime: '2023-02-06 09:10:19',
      organizationName: '研发部',
      sexName: '男',
      roles: [
        {
          roleId: 11,
          roleCode: 'user',
          roleName: '普通用户',
          comments: '普通用户',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:52',
          updateTime: '2020-03-21 15:16:02',
          userId: 44
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: true,
      accountNonExpired: true,
      credentialsNonExpired: true
    },
    {
      userId: 45,
      username: 'user05',
      password: '$2a$10$6bdw9kiSq6cefcwN1nvcyOyWxgKxNipVsR7M1QvmG9pPZ4ggldr4a',
      nickname: '用户五',
      avatar: null,
      sex: '2',
      phone: '12345678906',
      email: null,
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: null,
      introduction: null,
      organizationId: 32,
      status: 0,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-09-15 17:52:22',
      updateTime: '2023-02-06 09:10:21',
      organizationName: '研发部',
      sexName: '女',
      roles: [
        {
          roleId: 11,
          roleCode: 'user',
          roleName: '普通用户',
          comments: '普通用户',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:52',
          updateTime: '2020-03-21 15:16:02',
          userId: 45
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: true,
      accountNonExpired: true,
      credentialsNonExpired: true
    },
    {
      userId: 46,
      username: 'user06',
      password: '$2a$10$fKDoXZPU43tiFxXyzPXcu.kCpiv9ACtlgkxFeB/NBl4ti7GqI.EE.',
      nickname: '用户六',
      avatar: null,
      sex: '1',
      phone: '12345678907',
      email: null,
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: null,
      introduction: null,
      organizationId: 32,
      status: 0,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-09-15 17:53:31',
      updateTime: '2023-02-06 09:10:23',
      organizationName: '研发部',
      sexName: '男',
      roles: [
        {
          roleId: 11,
          roleCode: 'user',
          roleName: '普通用户',
          comments: '普通用户',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:52',
          updateTime: '2020-03-21 15:16:02',
          userId: 46
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: true,
      accountNonExpired: true,
      credentialsNonExpired: true
    },
    {
      userId: 47,
      username: 'user07',
      password: '$2a$10$R4JW6t3GK7fz3B830WsRI.uoW5LZq9EG.VAopRyKXVemXDkpybYni',
      nickname: '用户七',
      avatar: null,
      sex: '1',
      phone: '12345678908',
      email: null,
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: null,
      introduction: null,
      organizationId: 33,
      status: 0,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-10-20 23:28:40',
      updateTime: '2023-02-06 09:10:25',
      organizationName: '研发一组',
      sexName: '男',
      roles: [
        {
          roleId: 11,
          roleCode: 'user',
          roleName: '普通用户',
          comments: '普通用户',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:52',
          updateTime: '2020-03-21 15:16:02',
          userId: 47
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: true,
      accountNonExpired: true,
      credentialsNonExpired: true
    },
    {
      userId: 48,
      username: 'user08',
      password: '$2a$10$AFQ5PLZCf.Y1N9vqoNIJouTTdydXyogoc3AG.7eJylS1LCSJnt7JW',
      nickname: '用户八',
      avatar: null,
      sex: '2',
      phone: '12345678909',
      email: null,
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: null,
      introduction: null,
      organizationId: 33,
      status: 1,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-10-20 23:29:03',
      updateTime: '2023-06-13 21:57:35',
      organizationName: '研发一组',
      sexName: '女',
      roles: [
        {
          roleId: 11,
          roleCode: 'user',
          roleName: '普通用户',
          comments: '普通用户',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:52',
          updateTime: '2020-03-21 15:16:02',
          userId: 48
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: false,
      accountNonExpired: true,
      credentialsNonExpired: true
    },
    {
      userId: 49,
      username: 'user09',
      password: '$2a$10$jP8jv8A.uVSfKFzVpoNgmetdTK9pMAMjJh5wEQLH.sFVdMDILaXMS',
      nickname: '用户九',
      avatar: null,
      sex: '2',
      phone: '12345678910',
      email: null,
      emailVerified: 0,
      realName: null,
      idCard: null,
      birthday: null,
      introduction: null,
      organizationId: 34,
      status: 0,
      deleted: 0,
      tenantId: 4,
      createTime: '2020-10-20 23:29:30',
      updateTime: '2023-02-06 09:10:29',
      organizationName: '研发二组',
      sexName: '女',
      roles: [
        {
          roleId: 11,
          roleCode: 'user',
          roleName: '普通用户',
          comments: '普通用户',
          deleted: 0,
          tenantId: 4,
          createTime: '2020-02-26 15:18:52',
          updateTime: '2020-03-21 15:16:02',
          userId: 49
        }
      ],
      authorities: null,
      enabled: true,
      accountNonLocked: true,
      accountNonExpired: true,
      credentialsNonExpired: true
    }
  ],
  total: 13
};
